#if !canImport(ObjectiveC)
import XCTest

extension ArtifactBundleGenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArtifactBundleGenTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArtifactBundleGenTests.__allTests__ArtifactBundleGenTests),
    ]
}
#endif
